### ISSUE TITLE
High CPU and Memory usage due to develop container

### ISSUE THREAD

**Issue by jakubgs** [acid-info/logos-press-engine#217]
### Summary:
Today I found the `develop` container using most of the CPU and Memory on the host:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/67d3f844-989d-42f0-b42a-ced46f846cc0)

And spewing these logs:
```
RuntimeError: unreachable
    at wasm://wasm/005420d6:wasm-function[1077]:0x135a01
    at fM (/app/.next/server/pages/api/og.js:66:56317)
    at e.wbg.__wbindgen_string_get (/app/.next/server/pages/api/og.js:66:61187)
    at wasm://wasm/005420d6:wasm-function[30]:0x3fcde
    at new fH (/app/.next/server/pages/api/og.js:66:58408)
    at new f1 (/app/.next/server/pages/api/og.js:66:62302)
    at pr (/app/.next/server/pages/api/og.js:66:64887)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.start (/app/.next/server/pages/api/og.js:66:65273)
RuntimeError: unreachable
    at wasm://wasm/005420d6:wasm-function[27]:0x38c4e
    at wasm://wasm/005420d6:wasm-function[30]:0x3fdcc
    at new fH (/app/.next/server/pages/api/og.js:66:58408)
    at new f1 (/app/.next/server/pages/api/og.js:66:62302)
    at pr (/app/.next/server/pages/api/og.js:66:64887)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.start (/app/.next/server/pages/api/og.js:66:65273)
```
Restart helped, at least for now.

### Environment:
- Operating System: `Alpine Linux 3.17`
- Project Version: `sha256:221faa7c3b63afc28ddb3788800874d001ef5cc720a37539e510de7161e8331c`

**Comment by jakubgs** [comment]
It appears this issue has not really been resolved, this is from today:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/bde38892-2541-4d84-9370-c61f18778b0f)

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/5e39b60f-fb34-420e-8c64-97295804b908)

Very high CPU and Memory usage spike. CPU eventually settles but memory is not freed.

**Comment by jakubgs** [comment]
I moved `logos-press-engine` and `free-technology` setups to a separate host due to these memory issues over a week ago.

- [`infra-misc#e7be53f6`](https://github.com/status-im/infra-misc/commit/e7be53f6) - aptly-server: add broken Status logo image

Which was a good move, because now the persistent memory issues do not affect other websites.

This is the `node-01.do-ams3.press.misc` host right now:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/c7a4cf40-6a5e-4473-998f-74cd644836a1)

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/8dcc934b-c92c-4d33-902a-55c91de0b7a3)

Can devs here investigate this?

**Comment by jakubgs** [comment]
Here's `free-technology` container:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/ee408223-b2a5-4787-9e03-83255e08cf1e)

And here's `logos-press-engine` container over 7 days:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/821d8ec6-e893-4516-9dd1-6704cfa96efa)

**Comment by jakubgs** [comment]
You can find all the logs on Kibana:
https://kibana.infra.status.im/goto/7939e460-d740-11ee-aaa4-85391103106b

But currently there's barely any logs, and the containers are behaving so far:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/6434139e-81b6-48df-8a07-4c0eadfadf18)

Here's the current trend:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/a52bdca4-3f32-4fea-a534-e544887f7535)

https://grafana.infra.status.im/d/QCTZ8-Vmk/single-host-dashboard?orgId=1&refresh=1m&var-host=node-01.do-ams3.press.misc&from=1708633580552&to=1709238380552

Ignore the drop off a the end, we are having issues with our metrics cluster: https://github.com/status-im/infra-hq/issues/125

**Comment by jakubgs** [comment]
I don't believe this issue is specific to `develop`, it was simply first observed on `develop`.

If you look at a 30 day graph you see it always goes up to the limit of 4 GB and releases memory only after restart:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/2ef3621b-b3f9-4b14-a3c0-bbce6ab29f73)

Ignore the two big spikes at the end, that's an artifact due to metrics cluster latency.

The host is constantly using pretty much all the SWAP memory:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/9747e895-1bca-4065-b23a-66e8237f0d65)

**Comment by siddarthkay** [comment]
Hey @jinhojang6 : I was planning on assigning this to myself and to begin investigating this issue if you don't mind.
Also would you have any additional notes other than what is already logged in this issue ?

Thank you.

**Comment by siddarthkay** [comment]
yeah my money was on nextjs.. although upgrading to 14 would be a disruptive change no @jinhojang6  ?
since it uses an experimental router and everything ?

**Comment by siddarthkay** [comment]
I am always up for upgrading stuff :D @jinhojang6 
I was trying to recreate the problem locally by profiling the app and trying to find out exactly where the leak comes from.
But yeah planning for an upgrade is always good and something that we should often do.

**Comment by siddarthkay** [comment]
That was quick! @jinhojang6 
yes please go on :)

**Comment by jakubgs** [comment]
Can we apply the same upgrade to the software used for https://free.technology/ as well?

**Comment by jakubgs** [comment]
Seems like we are swapping again:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/25b795c3-f3d3-42e2-943e-f90434c05a5f)

Memory usage has been growing for the past 4 days:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/9e8f67c9-bc91-467c-9340-e3b52ef240fa)

Not sure if this is resolved. We could try getting a bigger host, but I really don't think you need ~4 GB to run a simple website.

**Comment by yakimant** [comment]
What's interesting, that's logos press engine this time, but not free technology:
<img width="676" alt="Screenshot 2024-03-25 at 12 29 04" src="https://github.com/acid-info/logos-press-engine/assets/1529006/002fae60-34e1-44df-a707-4d098ea6c639">

**Comment by yakimant** [comment]
Looks like NextJS upgrade doesn't solve the issue.
I will add a daily containers restart for now.

**Comment by siddarthkay** [comment]
Okay I'll resume profiling the web app then.

**Comment by yakimant** [comment]
Restart added: https://github.com/status-im/infra-misc/commit/dbf648695214aaf47fb08a9bc6895938e02700bc

Let's remove if the issue is fixed.

**Comment by yakimant** [comment]
Nice, 100Mb per container, how it is supposed to be:
<img width="1359" alt="Screenshot 2024-03-27 at 15 31 05" src="https://github.com/acid-info/logos-press-engine/assets/1529006/4e4c50b3-3a7f-47af-8a68-4745927570f6">

**Comment by jakubgs** [comment]
It appears the problem still persists:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/5575632f-79fb-4a88-a753-1caa839ef32f)

The source appears to be the `4111750` process from `logos-press-engine-master` container:
```
jakubgs@node-01.do-ams3.press.misc:~ % d top logos-press-engine-master
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
dockrem+            4110682             4110616             0                   00:00               ?                   00:00:13            node /opt/yarn-v1.22.19/bin/yarn.js start
dockrem+            4111750             4110682             4                   00:00               ?                   00:26:29            next-server
```
Here's the graph:

![image](https://github.com/acid-info/logos-press-engine/assets/2212681/c40e837f-9bb5-45cf-b053-f4749c92dd54)

It seems like the daily restart is not enough.

**Comment by jakubgs** [comment]
The logs contain a lot of those:
```
